[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "fastapi>=0.115.12",
    "openai>=1.70.0",
    "pydantic>=2.11.2",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.0",
]
